### ISSUE TITLE
Doesn't work on XNPH38R

### ISSUE THREAD

**Issue by XenGi** [julian-klode/bacon-superuser#2]
Tried this on the newest version but recovery says that the footer isn't correct and doesn't want to flash the zip.
The signature verification fails with the signed and the unsigned package, which seems correct because I don't have the correct keys to sign the package. I think I need the same keys that cyanogen used to signed the rest of the system.

Which keys did you use to sign your package?

What I tried:

I changed ```VERSION := XNPH30O``` to ```VERSION := XNPH38R``` in ```Makefile``` and updated ```NDK_BUILD    := /opt/android-ndk/ndk-build```.
```make light``` and ```make full``` seems to work correct but the produced zips doesn't work.

**Comment by julian-klode** [comment]
You need to use a custom recovery, not the Cyanogen recovery.
