### ISSUE TITLE
On YOG7DAS2K1, various settings are no longer visible when this superuser (ver. for YOG4PAS3JL) is installed

### ISSUE THREAD

**Issue by Natanji** [julian-klode/bacon-superuser#3]
Examples that I've found so far:
-On-screen navigation bar is gone
-"Double tap to wake" option is gone

It's a really strange problem, because why does installing some superuser disable these options? Even if it's for version YOG4PAS3JL.

**Comment by julian-klode** [comment]
I just rebuilt the image with the freshly published debuggable boot image for YOG7DAS2K1:

http://jak-linux.org/cm/cm-unofficial-12.1-YOG7DAS2K1-bacon-signed-superuser.zip

Could you check if the bug still exists? I can't test right now.

**Comment by Natanji** [comment]
Yup, that totally fixed it. Thanks!

Would still be interesting to know why this even happens. I previously tested just deleting /system/xbin/su from my system and rebooting, but that did not bring the options back. Just applying that update did. Any idea what might have been happening there?

**Comment by julian-klode** [comment]
It's probably not root related: It's flashing the debuggable boot image from Cyanogen, and that seems to have caused the issues.
